version: '3.8'

services:
  db:
    image: postgres:15
    container_name: auth_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: auth_service_db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  app:
    build: .
    container_name: auth-service
    depends_on:
      - db
    environment:
      SERVER_PORT: 8080
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: auth_service_db
      DB_SSL_MODE: disable
      JWT_ACCESS_SECRET: my_super_secret_access_key
      JWT_ACCESS_EXPIRY: 15m
      JWT_REFRESH_SECRET: my_super_secret_refresh_key
      JWT_REFRESH_EXPIRY: 720h
      WEBHOOK_URL: https://webhook.site/your-test-id
    ports:
      - "8080:8080"
    working_dir: /app
    command: ./auth-service

volumes:
  postgres-data:
